name: Checks

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.branch }}

jobs:
  build:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/browser-tabletop/.github@main

      - name: Build client
        run: npm run build

  commitlint:
    name: CommitLint
    if: ${{ contains(github.event_name, 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/browser-tabletop/.github@main

      - name: Lint pull request title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/browser-tabletop/.github@main

      - name: ESLint
        run: npx eslint .

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/browser-tabletop/.github@main

      - name: Prettier
        run: npx prettier -lu .

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/browser-tabletop/.github@main

      - name: Run unit tests
        run: npm run coverage
